package frc.robot;


import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.button.JoystickButton;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.commands.*;
import frc.robot.subsystems.*;

// The structure of the robot (including subsystems, commands, and button mappings) should be declared here.
public class RobotContainer {

  private static RobotContainer m_robotContainer = new RobotContainer();

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
  // The robot's subsystems
  private final Shooter m_shooter = new Shooter();
  private final Feeder m_feeder = new Feeder();
  private final Drivetrain m_drivetrain = new Drivetrain();
  private final Light m_light = new Light();

  // Joysticks
  private final XboxController xboxController = new XboxController(0);
  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

  // A chooser for autonomous commands
  SendableChooser<Command> m_chooser = new SendableChooser<>();

  // The container for the robot.  Contains subsystems, OI devices, and commands.
  private RobotContainer() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
    // SmartDashboard Buttons
    SmartDashboard.putData("Drive", new Drive(m_drivetrain));
    SmartDashboard.putData("FeederOn", new FeederOn(m_feeder));
    SmartDashboard.putData("ShooterOnGreen", new ShooterOnGreen(m_shooter));
    SmartDashboard.putData("ShooterOnYellow", new ShooterOnYellow(m_shooter));
    SmartDashboard.putData("ShooterOnBlue", new ShooterOnBlue(m_shooter));
    SmartDashboard.putData("ShooterOnRed", new ShooterOnRed(m_shooter));
    SmartDashboard.putData("ShooterOff", new ShooterOff(m_shooter));
    SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
    SmartDashboard.putData("DriveToggle", new DriveToggle(m_drivetrain));
    SmartDashboard.putData("LightToggle", new LightToggle(m_light));
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD

    // Configure the button bindings
    configureButtonBindings();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND
    // Configure default commands
    m_drivetrain.setDefaultCommand(new Drive(m_drivetrain));
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
    // Configure autonomous sendable chooser
    m_chooser.setDefaultOption("Autonomous Command", new AutonomousCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    SmartDashboard.putData("Auto Mode", m_chooser);
  }

  public static RobotContainer getInstance() {
    return m_robotContainer;
  }

  private void configureButtonBindings() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
    // Create some buttons
    final JoystickButton back_DriveToggle = new JoystickButton(xboxController, XboxController.Button.kBack.value);        
    back_DriveToggle.whenPressed(new DriveToggle(m_drivetrain), true);
    
    final JoystickButton start_LightToggle = new JoystickButton(xboxController, XboxController.Button.kStart.value);        
    start_LightToggle.whenPressed(new LightToggle(m_light), true);

    final JoystickButton bumperRight_FeederOn = new JoystickButton(xboxController, XboxController.Button.kBumperRight.value);        
    bumperRight_FeederOn.whileHeld(new FeederOn(m_feeder), true);

    final JoystickButton bumperLeft_ShooterOff = new JoystickButton(xboxController, XboxController.Button.kBumperLeft.value);        
    bumperLeft_ShooterOff.whenPressed(new ShooterOff(m_shooter), true);

    final JoystickButton b_ShooterOnRed = new JoystickButton(xboxController, XboxController.Button.kB.value);        
    b_ShooterOnRed.whenPressed(new ShooterOnRed(m_shooter), true);

    final JoystickButton x_ShooterOnBlue = new JoystickButton(xboxController, XboxController.Button.kX.value);        
    x_ShooterOnBlue.whenPressed(new ShooterOnBlue(m_shooter), true);

    final JoystickButton y_ShooterOnYellow = new JoystickButton(xboxController, XboxController.Button.kY.value);        
    y_ShooterOnYellow.whenPressed(new ShooterOnYellow(m_shooter), true);

    final JoystickButton a_ShooterOnGreen = new JoystickButton(xboxController, XboxController.Button.kA.value);        
    a_ShooterOnGreen.whenPressed(new ShooterOnGreen(m_shooter), true);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
  }

  // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
  public XboxController getXboxController() {
    return xboxController;
  }
  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

  // Passes the autonomous command to the Main class
  public Command getAutonomousCommand() {
    // The selected command will be run in autonomous
    return m_chooser.getSelected();
  }
}
